name: QuickShop Security Scans

on:
  push:
    branches: [ "main", "staging" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Initialize CodeQL (SAST)
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    - name: Run Dependency Vulnerability Scan (SCA)
      run: |
        dotnet list package --vulnerable --include-transitive
